# Generated by Django 5.1 on 2024-08-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
